apiVersion: v1
kind: PersistentVolume
metadata:
  name: {PV_NAME}
spec:
  capacity:
    storage: 10Gi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /u0{MAJOR_DISK}/{DIR_NAME}
    server: {NFS_HOST}
  persistentVolumeReclaimPolicy: Retain
